In [115]:
import os  
import csv
import numpy
def load_song_path(dir_path):
    main_dir_path = dir_path
    os.chdir(main_dir_path)
    dir_list = os.listdir()
    song_path = []
    for dir_name in dir_list:
        song_path.append(main_dir_path + '\\' + dir_name)
    return song_path
songs_path = load_song_path("D:\\tandon\\AI_for_game\\osu_project\\139677 Demetori - Hoshi no Utsuwa - Casket of Star")


['D:\\tandon\\AI_for_game\\osu_project\\139677 Demetori - Hoshi no Utsuwa - Casket of Star\\139677 Demetori - Hoshi no Utsuwa ~ Casket of Star']


In [122]:

def load_training_tensor(songs_path):
    data_input = numpy.array([])
    data_output = numpy.array([])
    for song_path in songs_path:
        os.chdir(song_path)
        for dirpaths, dirnames, filenames in os.walk(".", topdown = False):
            for filename in filenames:
                if filename.endswith('.csv'):
                    print(filename)
                    print (song_path)
                    content_matrix = numpy.loadtxt(song_path+'\\'+filename,delimiter=",",skiprows=0)
                    #print(content_matrix)
                    x = numpy.array(content_matrix)
                    x.resize(24000,18)
                    X = x[:,0:-3]
                    Y = x[:,-3:]
                    print(X)
                    data_input = numpy.vstack([data_input, X]) if data_input.size else X
                    data_output = numpy.vstack([data_output, Y]) if data_output.size else Y
    data_input = numpy.array(data_input)
    data_output = numpy.array(data_output)
    numpy.savetxt('D:\\tandon\\AI_for_game\\osu_project\\training_input.csv', data_input, delimiter = ',') 
    numpy.savetxt('D:\\tandon\\AI_for_game\\osu_project\\training_output.csv', data_output, delimiter = ',')
load_training_tensor(songs_path)


Train_result_ Lunatic.csv
D:\tandon\AI_for_game\osu_project\139677 Demetori - Hoshi no Utsuwa - Casket of Star\139677 Demetori - Hoshi no Utsuwa ~ Casket of Star
[[  0.00000000e+00   0.00000000e+00   1.00000000e+00 ...,  -1.84297022e-14
   -6.88338275e-15   1.15463195e-14]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00 ...,  -1.84297022e-14
   -6.88338275e-15   1.15463195e-14]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00 ...,  -1.84297022e-14
   -6.88338275e-15   1.15463195e-14]
 ..., 
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00 ...,   0.00000000e+00
    0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00 ...,   0.00000000e+00
    0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00 ...,   0.00000000e+00
    0.00000000e+00   0.00000000e+00]]
Train_result_Normal.csv
D:\tandon\AI_for_game\osu_project\139677 Demetori - Hoshi no Utsuwa - Casket of Star\139677 Demetori - Hoshi no Utsuwa ~ Casket of Sta

In [70]:
fakedata = [[1,2,3,1,2,3,1,2,3,1,2,3],[1,2,3,1,2,3,1,2,3,1,2,3]]
file_path = 'D:\\Program Files\\osu!\\Songs\\13019 Daisuke Achiwa - BASARA\\fake.csv'

numpy.savetxt(file_path, fakedata, delimiter=',')
content_matrix = numpy.loadtxt(open(song_path+'\\'+filename,"rb"),delimiter=",",skiprows=0)

In [114]:
fakedata = [[1,2,3,1,2,3,1,2,3,1,2,4],[1,2,3,1,2,3,1,2,3,1,2,4]]
x = numpy.array(fakedata)
x.resize(4,12)
X = x[:,0:-3]
Y = x[:,-3:]
print(X)
print(Y)

[[1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
[[1 2 4]
 [1 2 4]
 [0 0 0]
 [0 0 0]]
